name: Create and push release
on:
  push:
    tags:
      - v*

permissions: 
  contents: write

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    outputs: 
        upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2

  build:
    name: Build artifacts
    runs-on: ubuntu-latest
    needs: create-release
    strategy:
      matrix: 
        runtime: [win-x64, linux-x64, osx-x64]
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - name: Build
        run: >-
          dotnet publish
          GridStickerMaker/GridStickerMaker.fsproj
          --configuration Release
          --output out
          --runtime ${{ matrix.runtime }}
      - name: Create zip
        if: matrix.runtime == 'win-x64'
        run: zip -r "GridStickerMaker-${{ matrix.runtime }}.zip" out
      - name: Upload zip
        if: matrix.runtime == 'win-x64'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: GridStickerMaker-${{ matrix.runtime }}.zip
          asset_name: GridStickerMaker-${{ matrix.runtime }}.zip
          asset_content_type: application/zip
      - name: Create gz
        if: matrix.runtime != 'win-x64'
        run: tar -czf "GridStickerMaker-${{ matrix.runtime }}.tar.gz" out
      - name: Upload gz
        if: matrix.runtime != 'win-x64'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: GridStickerMaker-${{ matrix.runtime }}.tar.gz
          asset_name: GridStickerMaker-${{ matrix.runtime }}.tar.gz
          asset_content_type: application/gzip
